// ponytail: heuristic keyword list, not NLP. Extend array to catch more terms.
export const KEYWORDS = [
  { label: 'JavaScript', aliases: ['javascript'] },
  { label: 'TypeScript', aliases: ['typescript'] },
  { label: 'Python', aliases: ['python'] },
  { label: 'Rust', aliases: ['rust'] },
  { label: 'Golang', aliases: ['golang', 'go lang'] },
  { label: 'Java', aliases: ['java'] },
  { label: 'Kotlin', aliases: ['kotlin'] },
  { label: 'Swift', aliases: ['swift'] },
  { label: 'C#', aliases: ['c#', 'csharp'] },
  { label: 'C++', aliases: ['c++'] },
  { label: 'PHP', aliases: ['php'] },
  { label: 'Ruby', aliases: ['ruby'] },
  { label: 'Elixir', aliases: ['elixir'] },
  { label: 'React', aliases: ['react', 'reactjs'] },
  { label: 'Next.js', aliases: ['next.js', 'nextjs'] },
  { label: 'Vue', aliases: ['vue', 'vuejs'] },
  { label: 'Angular', aliases: ['angular'] },
  { label: 'Svelte', aliases: ['svelte'] },
  { label: 'Node.js', aliases: ['node.js', 'nodejs'] },
  { label: 'Deno', aliases: ['deno'] },
  { label: 'Bun', aliases: ['bun.js', 'bun runtime'] },
  { label: 'Django', aliases: ['django'] },
  { label: 'Flask', aliases: ['flask'] },
  { label: 'FastAPI', aliases: ['fastapi'] },
  { label: 'Spring', aliases: ['spring boot', 'spring framework'] },
  { label: 'Laravel', aliases: ['laravel'] },
  { label: 'Docker', aliases: ['docker'] },
  { label: 'Kubernetes', aliases: ['kubernetes', 'k8s'] },
  { label: 'Terraform', aliases: ['terraform'] },
  { label: 'AWS', aliases: ['aws', 'amazon web services'] },
  { label: 'Azure', aliases: ['azure'] },
  { label: 'GCP', aliases: ['gcp', 'google cloud'] },
  { label: 'PostgreSQL', aliases: ['postgresql', 'postgres'] },
  { label: 'MySQL', aliases: ['mysql'] },
  { label: 'MongoDB', aliases: ['mongodb', 'mongo'] },
  { label: 'Redis', aliases: ['redis'] },
  { label: 'GraphQL', aliases: ['graphql'] },
  { label: 'gRPC', aliases: ['grpc'] },
  { label: 'Git', aliases: ['git'] },
  { label: 'GitHub', aliases: ['github'] },
  { label: 'GitLab', aliases: ['gitlab'] },
  { label: 'CI/CD', aliases: ['ci/cd', 'ci-cd'] },
  { label: 'Linux', aliases: ['linux'] },
  { label: 'DevOps', aliases: ['devops'] },
  { label: 'Machine Learning', aliases: ['machine learning'] },
  { label: 'IA/LLM', aliases: ['ia', 'inteligência artificial', 'llm'] },
  { label: 'ChatGPT', aliases: ['chatgpt'] },
  { label: 'Claude', aliases: ['claude ai', 'claude code', 'anthropic'] },
  { label: 'Copilot', aliases: ['copilot'] },
  { label: 'Blockchain', aliases: ['blockchain'] },
  { label: 'Web3', aliases: ['web3'] },
  { label: 'Flutter', aliases: ['flutter'] },
  { label: 'React Native', aliases: ['react native'] },
  { label: 'Tailwind', aliases: ['tailwind'] },
  { label: 'SQL', aliases: ['sql'] },
  { label: 'NoSQL', aliases: ['nosql'] },
  { label: 'Microservices', aliases: ['microservi'] },
  { label: 'Serverless', aliases: ['serverless'] },
  { label: 'WebAssembly', aliases: ['webassembly', 'wasm'] },
  { label: 'Vite', aliases: ['vite'] },
  { label: 'Webpack', aliases: ['webpack'] },
  { label: 'ESLint', aliases: ['eslint'] },
  { label: 'Vitest', aliases: ['vitest'] },
  { label: 'Playwright', aliases: ['playwright'] },
  { label: 'Cypress', aliases: ['cypress'] },
  { label: 'Figma', aliases: ['figma'] },
  { label: 'Vim/Neovim', aliases: ['neovim', 'vim'] },
  { label: 'VSCode', aliases: ['vscode', 'vs code'] },
  { label: 'Supabase', aliases: ['supabase'] },
  { label: 'Vercel', aliases: ['vercel'] },
  { label: 'Firebase', aliases: ['firebase'] },
];
